# Generated by Django 4.0.4 on 2022-05-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='gamer',
        ),
    ]
