# Generated by Django 4.0.4 on 2022-05-11 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0002_remove_photo_gamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.gamer'),
            preserve_default=False,
        ),
    ]
